Using tabs instead of whitespace

diff --git a/tests/009_script_listings b/tests/009_script_listings
--- a/tests/009_script_listings
+++ b/tests/009_script_listings
@@ -2,6 +2,6 @@
 
 goal "Script listing"
 {
-    echo "Test is not defined yet: failed" | INDENT
-    exit 1
+	echo "Test is not defined yet: failed" | INDENT
+	exit 1
 }
diff --git a/tests/envTest b/tests/envTest
--- a/tests/envTest
+++ b/tests/envTest
@@ -3,89 +3,89 @@
 CODE_EXIT=1
 
 function INDENT {
-    sed "s/^/$( printf "    %.0s" $( seq 0 $1 ) )/g"
+	sed "s/^/$( printf "	%.0s" $( seq 0 $1 ) )/g"
 }
 
 function rmTemp() {
-    rm $TempFile
-    rm $TempDir -r
-    exit $CODE_EXIT
+	rm $TempFile
+	rm $TempDir -r
+	exit $CODE_EXIT
 }
 
 LEVEL=0
 function goal() {
-    echo $1 | INDENT $LEVEL
-    LEVEL=$(( LEVEL + 1 ))
+	echo $1 | INDENT $LEVEL
+	LEVEL=$(( LEVEL + 1 ))
 }
 
 function goalend() {
-    LEVEL=$(( LEVEL - 1 ))
+	LEVEL=$(( LEVEL - 1 ))
 }
 
 function exitOk() {
-    goalend
-    if [ $1 != "0" ]; then
-        [ -n "$2" ] && echo $2: failed | INDENT $LEVEL
-        exit 1
-    fi
-    echo ok | INDENT $LEVEL
+	goalend
+	if [ $1 != "0" ]; then
+		[ -n "$2" ] && echo $2: failed | INDENT $LEVEL
+		exit 1
+	fi
+	echo ok | INDENT $LEVEL
 }
 
 function exitAtPoint() {
-    FILE=$2
-    sed -i \
-        -e "s/\(.\+\)\/\/ TEST_EXIT_POINT_\([0-9]\+\)/\/\/ TEST_EXIT_POINT_\2/g" \
-        -e "s/\/\/ TEST_EXIT_POINT_$1/setTimeout( () => process.exit(), 1000 ); return; \/\/ TEST_EXIT_POINT_$1/g" \
-        $FILE
+	FILE=$2
+	sed -i \
+		-e "s/\(.\+\)\/\/ TEST_EXIT_POINT_\([0-9]\+\)/\/\/ TEST_EXIT_POINT_\2/g" \
+		-e "s/\/\/ TEST_EXIT_POINT_$1/setTimeout( () => process.exit(), 1000 ); return; \/\/ TEST_EXIT_POINT_$1/g" \
+		$FILE
 }
 
 function enScriptAt() {
-    FILE=$2
-    sed -i \
-        -e "s/\(.\+\)\/\/\?\* TEST_SCRIPT_POINT_\([0-9]\+\)/\/\* TEST_SCRIPT_POINT_\2/g" \
-        -e "s/\/\* TEST_SCRIPT_POINT_$1/\/\/\* TEST_SCRIPT_POINT_$1/g" \
-        $FILE
+	FILE=$2
+	sed -i \
+		-e "s/\(.\+\)\/\/\?\* TEST_SCRIPT_POINT_\([0-9]\+\)/\/\* TEST_SCRIPT_POINT_\2/g" \
+		-e "s/\/\* TEST_SCRIPT_POINT_$1/\/\/\* TEST_SCRIPT_POINT_$1/g" \
+		$FILE
 }
 
 
 function waitEnd() {
 
-    FILE=$1
-    TOTAL_WAITS=$2
-    WAIT_INT=$3
+	FILE=$1
+	TOTAL_WAITS=$2
+	WAIT_INT=$3
 
-    node $FILE &
+	node $FILE &
 
-    PID=$( ps -o pid,command | grep "node $FILE" | awk '{ print $1 }' | head -n 1 )
+	PID=$( ps -o pid,command | grep "node $FILE" | awk '{ print $1 }' | head -n 1 )
 
-    PROCESS_ENDED=0
-    l=$(( TOTAL_WAITS + 1 ))
-    for (( i=1; i<$l; i++ ))
-    do
-        echo "Waiting for $FILE to end, pid: $PID"
+	PROCESS_ENDED=0
+	l=$(( TOTAL_WAITS + 1 ))
+	for (( i=1; i<$l; i++ ))
+	do
+		echo "Waiting for $FILE to end, pid: $PID"
 
-        (kill -0 $PID 2>&1) >/dev/null
+		(kill -0 $PID 2>&1) >/dev/null
 
-        if [ $? != "0" ]; then
-            PROCESS_ENDED=1
-            break;
-        fi
+		if [ $? != "0" ]; then
+			PROCESS_ENDED=1
+			break;
+		fi
 
-        sleep $WAIT_INT
-    done
+		sleep $WAIT_INT
+	done
 
-    if [ $PROCESS_ENDED == "0" ]; then
-        echo -n "Process does not end itself. Killing it ..."
-        (kill -9 $PID 2>&1) >/dev/null
-        if [ $? == "0" ]; then
-            echo "done"
-        else
-            echo "failed"
-        fi
-        return 1
-    fi
+	if [ $PROCESS_ENDED == "0" ]; then
+		echo -n "Process does not end itself. Killing it ..."
+		(kill -9 $PID 2>&1) >/dev/null
+		if [ $? == "0" ]; then
+			echo "done"
+		else
+			echo "failed"
+		fi
+		return 1
+	fi
 
-    return 0
+	return 0
 }
 
 TARGET_TEST=$1
diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -6,80 +6,80 @@ SERVER_LOG=$( grep "var path = \"[^\"]\+\"" ./config/log.js | sed "s/.\+\"\([^\"
 TERM=0
 
 function error() {
-    CODE_EXIT=1
-    echo "Error: $1"
+	CODE_EXIT=1
+	echo "Error: $1"
 }
 
 function stopTest() {
-    if [ $1 != "0" ]; then
-        TERM=1
-    fi
+	if [ $1 != "0" ]; then
+		TERM=1
+	fi
 }
 
 function isServerOk() {
-    (kill -0 $PID 2>&1) >/dev/null
+	(kill -0 $PID 2>&1) >/dev/null
 }
 
 function begin_tests() {
-    echo
-    echo "Begin test"
-    CODE_EXIT=0
-    for i in $( ls tests | grep "^[0-9]\+_[^\.]\+$" | sort )
-    do
-        isServerOk
-        if [ $? != "0" ]; then
-            error "Server is down"
-            break;
-        fi
+	echo
+	echo "Begin test"
+	CODE_EXIT=0
+	for i in $( ls tests | grep "^[0-9]\+_[^\.]\+$" | sort )
+	do
+		isServerOk
+		if [ $? != "0" ]; then
+			error "Server is down"
+			break;
+		fi
 
-        echo -n "  $i: "
+		echo -n "  $i: "
 
-        RESULT=$( mktemp )
-        ./tests/envTest "./tests/$i" $SERVER_PORT $SERVER_LOG 2>&1 > $RESULT
+		RESULT=$( mktemp )
+		./tests/envTest "./tests/$i" $SERVER_PORT $SERVER_LOG 2>&1 > $RESULT
 
-        if [ $? != "0" ]; then
-            echo "failed"
-            CODE_EXIT=1
-            sed 's/^/    /g' $RESULT
-        else
-            echo "ok"
-        fi
+		if [ $? != "0" ]; then
+			echo "failed"
+			CODE_EXIT=1
+			sed 's/^/	/g' $RESULT
+		else
+			echo "ok"
+		fi
 
-        rm $RESULT
-    done
-    echo "Test End"
+		rm $RESULT
+	done
+	echo "Test End"
 }
 
 function serverEnd() {
-    echo -n "Killing the server: $PID ..."
+	echo -n "Killing the server: $PID ..."
 
-    (kill -9 $PID 2>&1) >/dev/null
+	(kill -9 $PID 2>&1) >/dev/null
 
-    isServerOk
-    if [ $? == "0" ]; then
-        echo "failed"
-    else
-        echo "done"
-    fi
+	isServerOk
+	if [ $? == "0" ]; then
+		echo "failed"
+	else
+		echo "done"
+	fi
 
-    echo "{CI_SECTION_START} access.log"
-    cat $SERVER_LOG;
-    echo "{CI_SECTION_END}"
+	echo "{CI_SECTION_START} access.log"
+	cat $SERVER_LOG;
+	echo "{CI_SECTION_END}"
 
-    sleep 1
+	sleep 1
 
-    exit $CODE_EXIT
+	exit $CODE_EXIT
 }
 
 function secScript() {
-    echo "{CI_SECTION_START} $1"
-    . ./tests/secscripts/$2
-    CODE_EXIT=$?
-    echo "{CI_SECTION_END}"
+	echo "{CI_SECTION_START} $1"
+	. ./tests/secscripts/$2
+	CODE_EXIT=$?
+	echo "{CI_SECTION_END}"
 
-    if [ $TERM = 1 ]; then
-        exit $CODE_EXIT
-    fi
+	if [ $TERM = 1 ]; then
+		exit $CODE_EXIT
+	fi
 }
 
 SERVER_OK=false
@@ -88,7 +88,7 @@ secScript Settings settings
 secScript nodeServer node_server
 
 if [ $SERVER_OK = true ]; then
-    echo "{CI_SECTION_START} Test"
-    begin_tests
-    echo "{CI_SECTION_END}"
+	echo "{CI_SECTION_START} Test"
+	begin_tests
+	echo "{CI_SECTION_END}"
 fi
